---
title: "Google Maps Reviews API"
author: "Andrew Taylor"
date: "6/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Packedges for using Google Place API
```{r cars}
library(googleway)
```

###Google Places API Key
```{r}
places_key <- "AIzaSyBBFwzmJVkSxiwctOG6UYZGeGjbZJ_IH_4" #shhhh don't tell anyone 
```

###OSR Organizations Names
Here we use a list of names from all organizations leading a session in Denver extracted from our blueprint4summer list. 
```{r}
names <- c("YMCA of Metropolitan Denver"
,"Coding with Kids"
,"City of Aurora - Recreation"
,"City of Aurora- Cultural Arts"
,"Bounce Stapleton"
,"Thorne Nature Experience"
,"Colorado Mountain Ranch"
,"Renaissance Adventures"
,"Childrens Peace Garden Summer Camps"
,"Boulder Rock Club"
,"Aerial Summer Camps"
,"Avid Adventure"
,"Boulder Country Day School Summer Camp"
,"Boulder JCC"
,"Eagle Lake Camps"
,"Colorado Honor Band Association"
,"Engineering for Kids Camp"
,"Denver Public Library"
,"FRIENDS FIRST, Inc."
,"Steve & Kates Camp"
,"The First Tee of Denver"
,"Denver Center for the Performing Arts - Education"
,"Metropolitan State University of Denver"
,"Cleo Parker Robinson Dance"
,"Scholars Unlimited"
,"Discovery Link Summer Camp - DPS Extended Learning and Community Schools" 
,"The Greenway Foundation: SPREE Summer Camps"
,"School of the Poetic City"
,"Summer Literacy Camps"
,"Childrens Museum of Denver"
,"Big as Life Music Summer Band"
,"Park Hill Dance Academy Dance Camp"
,"Evolution Youth Services"
,"Generation Teach"
,"Denver Parks & Recreation - Community Recreation"
,"Pop Culture Classroom"
,"Talk to the Camera"
,"Camp Invention - Steele Elementary"
,"Pi Q Math"
,"Bluff Lake Summer Camp"
,"JCC Camp Shai"
,"Colorado Academy"
,"Ta Da Gymnastics Summer Camp"
,"The GrowHaus"
,"Cheyenne Fencing Society and Modern Pentathlon Center"
,"Downtown Aquarium Sea Safari"
,"Denver Tour Club"
,"Outschool (online CLASSES)"
,"Stapleton Family Karate"
,"CU Denver: LYNX National Arts & Media Camps"
,"Center for Urban Education, Metropolitan State University of Denver"
,"Action Figurs Jr"
,"Center for Visual Art - MSU Denver"
,"Colorado Master Chess"
,"Play On! Performing Arts (Executive Arts LLC)"
,"Poudre Learning Centers Science in Nature Camps"
,"Mile High Academy Kids University"
,"Bricks Kidz"
,"Keystone Science School"
,"artSPARK"
,"Dinosaur Ridge"
,"Camp Wapiyapi")
```

###Google Place Searches
```{r}
google_places <- google_places(search_string = names[1],
                                location = c(39.7392,-104.9903), #lat / lon for denver
                                key = places_key) #returns a summary of places near denver that match the search string

placeID <- google_places$results[1,'place_id'] #makes an object out the place id so we can get review ids 
```

###Google Place Details
```{r}
google_details <- google_place_details(place_id = placeID, key = places_key)
reviews <- as.data.frame(google_details$result['reviews']) #very important we select by title since the data.frame length may vary by list 
reviews$place <- names[1]
```

###Putting it altogether in a loop
```{r}
library(plyr)
for (i in 1:(length(names))){
  google_places.i <- google_places(search_string = names[i],
                                location = c(39.7392,-104.9903),
                                key = places_key)
  if ((length(google_places.i$results)>0)){ #every so often there is a search string which is to specific and returns 0 results, so here we skip it
  placeID.i <- google_places.i$results[1,'place_id']
  google_details.i <- google_place_details(place_id = placeID.i, key = places_key)
  reviews.i <- as.data.frame(google_details.i$result['reviews'])
  if (length(reviews.i)>0){ #critical here, some have no reviews, if there are none we can't take em obvs, so here we skip
  reviews.i$place <- names[i]
  total_reviews <- rbind.fill(reviews.i,total_reviews)
  print(paste("suck it google",i)) #yea! With you're free helpful api. We keep the counter per iteration here because we're a small n and we want to track any breaks
  Sys.sleep(0.01)}}}
```

###Cleaning up the total reviews data for analysis
```{r}
colnames(total_reviews) <- c("Author_Name","Author_Url","Language","Profile_Photo_Url","Rating","Relative_Time","Review_Text","Review_Time","Organization")
google_reviews_denver <- total_reviews
```

###Write to csv
```{r}
write.csv(google_reviews_denver,"google_reviews_denver.csv")
```

