---
title: "N_Students_Access"
author: "Andrew Taylor"
date: "8/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###RDS Pull
```{r}
library(rgeos)
library(rgdal)
library(raster)
library(tidyverse)
library(RPostgreSQL)
# loads the PostgreSQL driver
drv <- dbDriver("PostgreSQL")

# creates a connection to the postgres database
# note that "con" will be used later in each connection to the database
con <- dbConnect(drv, dbname = "dssg2018uw",
                 host = "localhost", port = 9000,
                 user = user, password = password) #local source credentials

#get reschool_programs
reschool_programs <- dbGetQuery(con, "select * from clean.reschool_summer_programs")
acs_demographics <- dbGetQuery(con, "select * from clean.acs_demographics")
dps_demographics <- dbGetQuery(con, "select * from clean.dps_students")
dps_block_locations <- dbGetQuery(con, "select * from clean.dps_block_locations")


#disconnect
dbDisconnect(con) 
dbUnloadDriver(drv)
```

###Census Merge Driving
```{r}
#pre acs for merge
acs_demographics$id2 <- as.numeric(acs_demographics$id2)
acs_demographics <- acs_demographics[order(acs_demographics$id2),]
colnames(acs_demographics)[colnames(acs_demographics)=="id2"] <- "Id2"

#merge access index with census block data
driving_index <- driving_index[order(driving_index$Id2),]
acs_driving_AI <- merge(driving_index,acs_demographics,by="Id2")

#make an overall column
acs_driving_AI$AI_overall <- rowMeans(acs_driving_AI[,c("AI_has_nature_anycost",'AI_has_sports_anycost','AI_art_anycost','AI_academic_anycost')])
```

###Make n of school age people
```{r}
acs_driving_AI$student_n <- acs_driving_AI$age_less_18-acs_driving_AI$age_less_5
```

###Plot students by AI
```{r}
library(ggplot2)
acs_pop <- acs_driving_AI[c("student_n","Id2")]
test <- merge(driving_index,transit_index,by="Id2",all.x=TRUE)
test <- merge(test,acs_pop)
nbhds <- dfFinal
colnames(nbhds)[colnames(nbhds)=="bgroup_id2"] <- "Id2"
test <- merge(test,nbhds,by=c("Id2"))
quarter <- function(x){
  if(x<=25){
    return("0-25")
  }
  if(x>25 & x<=50){
    return("25-50")
  }
  if(x>50 & x<=75){
    return("50-75")
  }
  if(x>75 & x<=100){
    return("75-100")
  }
}

test$AI_driving_range <-sapply(test$AI_overall.x,quarter) 
test$AI_transit_range <- sapply(test$AI_overall.y,quarter)

ggplot(test, aes(y=test$student_n,x=test$AI_overall.x,color=test$outlier_nbhd))+geom_point()
```

